// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package inner is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	AgentReport
*/
package inner

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentReport struct {
	Addrs            []*AgentReport_Addr `protobuf:"bytes,1,rep,name=addrs" json:"addrs,omitempty"`
	Attrs            []*AgentReport_Node `protobuf:"bytes,2,rep,name=attrs" json:"attrs,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *AgentReport) Reset()                    { *m = AgentReport{} }
func (m *AgentReport) String() string            { return proto.CompactTextString(m) }
func (*AgentReport) ProtoMessage()               {}
func (*AgentReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AgentReport) GetAddrs() []*AgentReport_Addr {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *AgentReport) GetAttrs() []*AgentReport_Node {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type AgentReport_Addr struct {
	Mac              *string  `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	Ips              []string `protobuf:"bytes,2,rep,name=ips" json:"ips,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AgentReport_Addr) Reset()                    { *m = AgentReport_Addr{} }
func (m *AgentReport_Addr) String() string            { return proto.CompactTextString(m) }
func (*AgentReport_Addr) ProtoMessage()               {}
func (*AgentReport_Addr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *AgentReport_Addr) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *AgentReport_Addr) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

type AgentReport_Node struct {
	Attr             *uint32 `protobuf:"varint,1,opt,name=attr" json:"attr,omitempty"`
	Value            *uint64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AgentReport_Node) Reset()                    { *m = AgentReport_Node{} }
func (m *AgentReport_Node) String() string            { return proto.CompactTextString(m) }
func (*AgentReport_Node) ProtoMessage()               {}
func (*AgentReport_Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *AgentReport_Node) GetAttr() uint32 {
	if m != nil && m.Attr != nil {
		return *m.Attr
	}
	return 0
}

func (m *AgentReport_Node) GetValue() uint64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*AgentReport)(nil), "inner.AgentReport")
	proto.RegisterType((*AgentReport_Addr)(nil), "inner.AgentReport.Addr")
	proto.RegisterType((*AgentReport_Node)(nil), "inner.AgentReport.Node")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x58, 0x33, 0xf3, 0xf2, 0x52, 0x8b, 0x94, 0x96,
	0x30, 0x72, 0x71, 0x3b, 0xa6, 0xa7, 0xe6, 0x95, 0x04, 0xa5, 0x16, 0xe4, 0x17, 0x95, 0x08, 0xa9,
	0x71, 0xb1, 0x26, 0xa6, 0xa4, 0x14, 0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xeb,
	0x81, 0x95, 0xe9, 0x21, 0x29, 0xd1, 0x73, 0x04, 0xca, 0x83, 0xd5, 0x95, 0x94, 0x00, 0xd5, 0x31,
	0xe1, 0x54, 0xe7, 0x97, 0x9f, 0x92, 0x2a, 0xa5, 0xc0, 0xc5, 0x02, 0x56, 0xcf, 0xcd, 0xc5, 0x9c,
	0x9b, 0x98, 0x0c, 0x34, 0x95, 0x51, 0x83, 0x13, 0xc4, 0xc9, 0x2c, 0x80, 0x68, 0xe5, 0x94, 0x52,
	0xe6, 0x62, 0x01, 0xa9, 0x14, 0xe2, 0xe1, 0x62, 0x01, 0x99, 0x08, 0x56, 0xc2, 0x2b, 0xc4, 0xcb,
	0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0x54, 0xc4, 0xa8, 0xc1, 0x02, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xe9, 0x01, 0x5a, 0xbe, 0x00, 0x00, 0x00,
}
